# Force Prediction

Machine learning model and data pipeline for predicting profile at any given MVC level from motor neuron activations.

## Preprocessing

Sanitize and prepare all the data for the machine learning model. This is a crucial step in the machine learning pipeline. The quality of the data and the features used in the model will determine the model's performance.

### Conversion

Convert, process, and export processed original data to a more structured and useful format (pandas DataFrame).

In [47]:
import importlib
import sanitization.conversion

importlib.reload(sanitization.conversion)

from sanitization.conversion import Conversion

c = Conversion(prefix='sanitization')

c.cleanup_data() # cleans the data directory and prepares for processing
c.process_subjects() # processes each subject and exports to txt files

Skipping anestis as raw folder already exists
Skipping chris as raw folder already exists
Skipping dim_tselios as raw folder already exists
Skipping dwrotheos as raw folder already exists
Skipping giannatos as raw folder already exists
Skipping iatroudelis as raw folder already exists
Skipping kiosses as raw folder already exists
Skipping konstantopoulos as raw folder already exists
Skipping leonidas as raw folder already exists
Skipping malidakis as raw folder already exists
Skipping manos as raw folder already exists
Skipping mavrokefalidis as raw folder already exists
Skipping mpardas as raw folder already exists
Skipping nastos-jr as raw folder already exists
Skipping nastos-sr as raw folder already exists
Skipping nick as raw folder already exists
Skipping nikos as raw folder already exists
Skipping paliaxanis as raw folder already exists
Skipping pavlidis as raw folder already exists
Skipping periklis as raw folder already exists
Skipping polemarchakis as raw folder already exists
Skipping rafa as raw folder already exists
Skipping romas as raw folder already exists
Skipping thanasis as raw folder already exists

Processing data for anestis

Skipping 10.1.mat as it has already been processed
Skipping 10.2.mat as it has already been processed
Skipping 10.3.mat as it has already been processed
Skipping 20.1.mat as it has already been processed
Skipping 20.2.mat as it has already been processed
Skipping 20.3.mat as it has already been processed
Skipping 40.1.mat as it has already been processed
Skipping 40.2.mat as it has already been processed
Skipping 40.3.mat as it has already been processed
Skipping 5.1.mat as it has already been processed
Skipping 5.2.mat as it has already been processed
Skipping 5.3.mat as it has already been processed
Skipping 60.1.mat as it has already been processed
Skipping 60.2.mat as it has already been processed
Skipping 60.3.mat as it has already been processed
Processing MVC.1.mat (MVC: 100, Trial: 1)...
Processing MVC.2.mat (MVC: 100, Trial: 2)...
Successfully processed data for anestis

Processing data for chris

Skipping 10.1.mat as it has already been processed
Skipping 10.2.mat as it has already been processed
Skipping 10.3.mat as it has already been processed
Skipping 20.1.mat as it has already been processed
Skipping 20.2.mat as it has already been processed
Skipping 20.3.mat as it has already been processed
Skipping 40.1.mat as it has already been processed
Skipping 40.2.mat as it has already been processed
Skipping 40.3.mat as it has already been processed
Skipping 5.1.mat as it has already been processed
Skipping 5.2.mat as it has already been processed
Skipping 5.3.mat as it has already been processed
Skipping 60.1.mat as it has already been processed
Skipping 60.2.mat as it has already been processed
Skipping 60.3.mat as it has already been processed
Processing MVC.1.mat (MVC: 100, Trial: 1)...
Skipping MVC.2.mat as it has already been processed
Successfully processed data for chris

Processing data for dim_tselios

Skipping 10.1.mat as it has already been processed
Skipping 10.2.mat as it has already been processed
Skipping 10.3.mat as it has already been processed
Skipping 20.1.mat as it has already been processed
Processing 20.2.mat (MVC: 20, Trial: 2)...
Skipping 20.2.mat as no MVC data was found
Skipping 20.3.mat as it has already been processed
Skipping 40.1.mat as it has already been processed
Skipping 40.2.mat as it has already been processed
Skipping 40.3.mat as it has already been processed
Skipping 5.1.mat as it has already been processed
Skipping 5.2.mat as it has already been processed
Skipping 5.3.mat as it has already been processed
Skipping 60.1.mat as it has already been processed
Skipping 60.2.mat as it has already been processed
Skipping 60.3.mat as it has already been processed
Processing MVC.1.mat (MVC: 100, Trial: 1)...
Processing MVC.2.mat (MVC: 100, Trial: 2)...
Successfully processed data for dim_tselios

Processing data for dwrotheos

Skipping 10.1.mat as it has already been processed
Skipping 10.2.mat as it has already been processed
Skipping 10.3.mat as it has already been processed
Skipping 20.1.mat as it has already been processed
Skipping 20.2.mat as it has already been processed
Skipping 20.3.mat as it has already been processed
Skipping 40.1.mat as it has already been processed
Skipping 40.2.mat as it has already been processed
Skipping 40.3.mat as it has already been processed
Skipping 5.1.mat as it has already been processed
Skipping 5.2.mat as it has already been processed
Skipping 5.3.mat as it has already been processed
Skipping 60.1.mat as it has already been processed
Skipping 60.2.mat as it has already been processed
Skipping 60.3.mat as it has already been processed
Processing MVC.1.mat (MVC: 100, Trial: 1)...
Processing MVC.2.mat (MVC: 100, Trial: 2)...
Successfully processed data for dwrotheos

Processing data for giannatos

Skipping 10.1.mat as it has already been processed
Skipping 10.2.mat as it has already been processed
Skipping 10.3.mat as it has already been processed
Skipping 20.1.mat as it has already been processed
Skipping 20.2.mat as it has already been processed
Skipping 20.3.mat as it has already been processed
Skipping 40.1.mat as it has already been processed
Skipping 40.2.mat as it has already been processed
Skipping 40.3.mat as it has already been processed
Skipping 5.1.mat as it has already been processed
Skipping 5.2.mat as it has already been processed
Skipping 5.3.mat as it has already been processed
Skipping 60.1.mat as it has already been processed
Skipping 60.2.mat as it has already been processed
Skipping 60.3.mat as it has already been processed
Processing MVC.1.mat (MVC: 100, Trial: 1)...
Processing MVC.2.mat (MVC: 100, Trial: 2)...
Successfully processed data for giannatos

Processing data for iatroudelis

Skipping 10.1.mat as it has already been processed
Skipping 10.3.mat as it has already been processed
Skipping 20.1.mat as it has already been processed
Skipping 20.2.mat as it has already been processed
Skipping 20.3.mat as it has already been processed
Skipping 40.1.mat as it has already been processed
Skipping 40.2.mat as it has already been processed
Skipping 40.3.mat as it has already been processed
Skipping 5.1.mat as it has already been processed
Skipping 5.2.mat as it has already been processed
Skipping 5.3.mat as it has already been processed
Skipping 60.1.mat as it has already been processed
Skipping 60.2.mat as it has already been processed
Skipping 60.3.mat as it has already been processed
Processing MVC.1.mat (MVC: 100, Trial: 1)...
Processing MVC.2.mat (MVC: 100, Trial: 2)...
Successfully processed data for iatroudelis

Processing data for kiosses

Skipping 10.1.mat as it has already been processed
Skipping 10.2.mat as it has already been processed
Skipping 10.3.mat as it has already been processed
Skipping 20.1.mat as it has already been processed
Skipping 20.2.mat as it has already been processed
Skipping 20.3.mat as it has already been processed
Skipping 40.1.mat as it has already been processed
Skipping 40.2.mat as it has already been processed
Skipping 40.3.mat as it has already been processed
Skipping 5.1.mat as it has already been processed
Skipping 5.2.mat as it has already been processed
Skipping 5.3.mat as it has already been processed
Processing 60.1.mat (MVC: 60, Trial: 1)...
Skipping 60.1.mat as no MVC data was found
Skipping 60.2.mat as it has already been processed
Skipping 60.3.mat as it has already been processed
Processing MVC.1.mat (MVC: 100, Trial: 1)...
Processing MVC.2.mat (MVC: 100, Trial: 2)...
Successfully processed data for kiosses

Processing data for konstantopoulos

Skipping 10.1.mat as it has already been processed
Skipping 10.2.mat as it has already been processed
Skipping 10.3.mat as it has already been processed
Skipping 20.1.mat as it has already been processed
Skipping 20.2.mat as it has already been processed
Skipping 20.3.mat as it has already been processed
Skipping 40.1.mat as it has already been processed
Skipping 40.2.mat as it has already been processed
Skipping 40.3.mat as it has already been processed
Skipping 5.1.mat as it has already been processed
Skipping 5.2.mat as it has already been processed
Skipping 5.3.mat as it has already been processed
Skipping 60.1.mat as it has already been processed
Skipping 60.2.mat as it has already been processed
Skipping 60.3.mat as it has already been processed
Processing MVC.1.mat (MVC: 100, Trial: 1)...
Processing MVC.2.mat (MVC: 100, Trial: 2)...
Successfully processed data for konstantopoulos

Processing data for leonidas

Skipping 10.1.mat as it has already been processed
Skipping 10.2.mat as it has already been processed
Skipping 10.3.mat as it has already been processed
Skipping 20.1.mat as it has already been processed
Skipping 20.2.mat as it has already been processed
Skipping 20.3.mat as it has already been processed
Skipping 40.1.mat as it has already been processed
Skipping 40.2.mat as it has already been processed
Skipping 40.3.mat as it has already been processed
Skipping 5.1.mat as it has already been processed
Skipping 5.2.mat as it has already been processed
Skipping 5.3.mat as it has already been processed
Skipping 60.1.mat as it has already been processed
Skipping 60.2.mat as it has already been processed
Skipping 60.3.mat as it has already been processed
Processing MVC.1.mat (MVC: 100, Trial: 1)...
Processing MVC.2.mat (MVC: 100, Trial: 2)...
Successfully processed data for leonidas

Processing data for malidakis

Skipping 10.1.mat as it has already been processed
Skipping 10.2.mat as it has already been processed
Skipping 10.3.mat as it has already been processed
Skipping 20.1.mat as it has already been processed
Skipping 20.2.mat as it has already been processed
Skipping 20.3.mat as it has already been processed
Skipping 40.1.mat as it has already been processed
Skipping 40.2.mat as it has already been processed
Skipping 40.3.mat as it has already been processed
Skipping 5.1.mat as it has already been processed
Skipping 5.2.mat as it has already been processed
Skipping 5.3.mat as it has already been processed
Skipping 60.1.mat as it has already been processed
Skipping 60.2.mat as it has already been processed
Skipping 60.3.mat as it has already been processed
Processing MVC.1.mat (MVC: 100, Trial: 1)...
Processing MVC.2.mat (MVC: 100, Trial: 2)...
Successfully processed data for malidakis

Processing data for manos

Skipping 10.1.mat as it has already been processed
Skipping 20.3.mat as it has already been processed
Skipping 40.1.mat as it has already been processed
Skipping 5.1.mat as it has already been processed
Skipping 5.3.mat as it has already been processed
Skipping 60.1.mat as it has already been processed
Processing MVC.1.mat (MVC: 100, Trial: 1)...
Successfully processed data for manos

Processing data for mavrokefalidis

Skipping 10.1.mat as it has already been processed
Skipping 10.2.mat as it has already been processed
Skipping 10.3.mat as it has already been processed
Skipping 20.1.mat as it has already been processed
Skipping 20.2.mat as it has already been processed
Skipping 20.3.mat as it has already been processed
Skipping 40.1.mat as it has already been processed
Skipping 40.2.mat as it has already been processed
Skipping 40.3.mat as it has already been processed
Skipping 5.1.mat as it has already been processed
Skipping 5.2.mat as it has already been processed
Skipping 5.3.mat as it has already been processed
Skipping 60.1.mat as it has already been processed
Skipping 60.2.mat as it has already been processed
Skipping 60.3.mat as it has already been processed
Processing MVC.1.mat (MVC: 100, Trial: 1)...
Processing MVC.2.mat (MVC: 100, Trial: 2)...
Successfully processed data for mavrokefalidis

Processing data for mpardas

Skipping 10.1.mat as it has already been processed
Skipping 10.2.mat as it has already been processed
Skipping 10.3.mat as it has already been processed
Skipping 20.1.mat as it has already been processed
Skipping 20.2.mat as it has already been processed
Skipping 20.3.mat as it has already been processed
Skipping 40.1.mat as it has already been processed
Skipping 40.2.mat as it has already been processed
Skipping 40.3.mat as it has already been processed
Skipping 5.1.mat as it has already been processed
Skipping 5.2.mat as it has already been processed
Skipping 5.3.mat as it has already been processed
Skipping 60.1.mat as it has already been processed
Skipping 60.2.mat as it has already been processed
Skipping 60.3.mat as it has already been processed
Processing MVC.1.mat (MVC: 100, Trial: 1)...
Skipping MVC.2.mat as it has already been processed
Successfully processed data for mpardas

Processing data for nastos-jr

Skipping 10.1.mat as it has already been processed
Skipping 10.2.mat as it has already been processed
Skipping 10.3.mat as it has already been processed
Skipping 20.1.mat as it has already been processed
Skipping 20.2.mat as it has already been processed
Skipping 20.3.mat as it has already been processed
Skipping 40.1.mat as it has already been processed
Skipping 40.2.mat as it has already been processed
Skipping 40.3.mat as it has already been processed
Skipping 5.1.mat as it has already been processed
Skipping 5.2.mat as it has already been processed
Skipping 5.3.mat as it has already been processed
Skipping 60.1.mat as it has already been processed
Skipping 60.2.mat as it has already been processed
Skipping 60.3.mat as it has already been processed
Processing MVC.1.mat (MVC: 100, Trial: 1)...
Processing MVC.2.mat (MVC: 100, Trial: 2)...
Successfully processed data for nastos-jr

Processing data for nastos-sr

Skipping 10.1.mat as it has already been processed
Skipping 10.2.mat as it has already been processed
Skipping 10.3.mat as it has already been processed
Skipping 20.1.mat as it has already been processed
Skipping 20.2.mat as it has already been processed
Skipping 20.3.mat as it has already been processed
Skipping 40.1.mat as it has already been processed
Skipping 40.2.mat as it has already been processed
Skipping 40.3.mat as it has already been processed
Skipping 5.1.mat as it has already been processed
Skipping 5.2.mat as it has already been processed
Skipping 5.3.mat as it has already been processed
Skipping 60.1.mat as it has already been processed
Skipping 60.2.mat as it has already been processed
Skipping 60.3.mat as it has already been processed
Processing MVC.1.mat (MVC: 100, Trial: 1)...
Processing MVC.2.mat (MVC: 100, Trial: 2)...
Successfully processed data for nastos-sr

Processing data for nick

Processing 10.1.mat (MVC: 10, Trial: 1)...
Skipping 10.1.mat as no MVC data was found
Skipping 10.2.mat as it has already been processed
Skipping 10.3.mat as it has already been processed
Skipping 20.1.mat as it has already been processed
Skipping 20.2.mat as it has already been processed
Skipping 20.3.mat as it has already been processed
Skipping 40.1.mat as it has already been processed
Skipping 40.2.mat as it has already been processed
Skipping 40.3.mat as it has already been processed
Skipping 5.1.mat as it has already been processed
Skipping 5.2.mat as it has already been processed
Skipping 5.3.mat as it has already been processed
Skipping 60.1.mat as it has already been processed
Skipping 60.2.mat as it has already been processed
Skipping 60.3.mat as it has already been processed
Processing MVC.1.mat (MVC: 100, Trial: 1)...
Processing MVC.2.mat (MVC: 100, Trial: 2)...
Successfully processed data for nick

Processing data for nikos

Skipping 10.1.mat as it has already been processed
Skipping 10.2.mat as it has already been processed
Skipping 10.3.mat as it has already been processed
Skipping 20.1.mat as it has already been processed
Skipping 20.2.mat as it has already been processed
Skipping 20.3.mat as it has already been processed
Skipping 40.1.mat as it has already been processed
Skipping 40.2.mat as it has already been processed
Skipping 40.3.mat as it has already been processed
Skipping 5.1.mat as it has already been processed
Skipping 5.2.mat as it has already been processed
Skipping 5.3.mat as it has already been processed
Skipping 60.1.mat as it has already been processed
Skipping 60.2.mat as it has already been processed
Skipping 60.3.mat as it has already been processed
Processing MVC.1.mat (MVC: 100, Trial: 1)...
Processing MVC.2.mat (MVC: 100, Trial: 2)...
Processing MVC.3.mat (MVC: 100, Trial: 3)...
Successfully processed data for nikos

Processing data for paliaxanis

Skipping 10.1.mat as it has already been processed
Skipping 10.2.mat as it has already been processed
Skipping 10.3.mat as it has already been processed
Skipping 20.1.mat as it has already been processed
Skipping 20.2.mat as it has already been processed
Skipping 20.3.mat as it has already been processed
Skipping 40.1.mat as it has already been processed
Skipping 40.2.mat as it has already been processed
Skipping 40.3.mat as it has already been processed
Skipping 5.1.mat as it has already been processed
Skipping 5.2.mat as it has already been processed
Skipping 5.3.mat as it has already been processed
Skipping 60.1.mat as it has already been processed
Skipping 60.2.mat as it has already been processed
Skipping 60.3.mat as it has already been processed
Processing MVC.1.mat (MVC: 100, Trial: 1)...
Processing MVC.2.mat (MVC: 100, Trial: 2)...
Processing MVC.3.mat (MVC: 100, Trial: 3)...
Successfully processed data for paliaxanis

Processing data for pavlidis

Skipping 10.1.mat as it has already been processed
Skipping 10.2.mat as it has already been processed
Skipping 10.3.mat as it has already been processed
Skipping 20.1.mat as it has already been processed
Skipping 20.2.mat as it has already been processed
Skipping 20.3.mat as it has already been processed
Skipping 40.1.mat as it has already been processed
Skipping 40.2.mat as it has already been processed
Skipping 40.3.mat as it has already been processed
Skipping 5.1.mat as it has already been processed
Skipping 5.2.mat as it has already been processed
Skipping 5.3.mat as it has already been processed
Skipping 60.1.mat as it has already been processed
Skipping 60.2.mat as it has already been processed
Skipping 60.3.mat as it has already been processed
Processing MVC.1.mat (MVC: 100, Trial: 1)...
Skipping MVC.2.mat as it has already been processed
Processing MVC.3.mat (MVC: 100, Trial: 3)...
Successfully processed data for pavlidis

Processing data for periklis

Skipping 10.1.mat as it has already been processed
Skipping 10.2.mat as it has already been processed
Skipping 10.3.mat as it has already been processed
Skipping 20.1.mat as it has already been processed
Skipping 20.2.mat as it has already been processed
Skipping 20.3.mat as it has already been processed
Skipping 40.1.mat as it has already been processed
Skipping 40.2.mat as it has already been processed
Skipping 40.3.mat as it has already been processed
Skipping 5.1.mat as it has already been processed
Skipping 5.2.mat as it has already been processed
Skipping 5.3.mat as it has already been processed
Skipping 60.1.mat as it has already been processed
Skipping 60.2.mat as it has already been processed
Skipping 60.3.mat as it has already been processed
Processing MVC.1.mat (MVC: 100, Trial: 1)...
Processing MVC.2.mat (MVC: 100, Trial: 2)...
Processing MVC.3.mat (MVC: 100, Trial: 3)...
Successfully processed data for periklis

Processing data for polemarchakis

Skipping 10.1.mat as it has already been processed
Skipping 10.2.mat as it has already been processed
Skipping 10.3.mat as it has already been processed
Skipping 20.1.mat as it has already been processed
Skipping 20.2.mat as it has already been processed
Skipping 20.3.mat as it has already been processed
Skipping 40.1.mat as it has already been processed
Skipping 40.2.mat as it has already been processed
Skipping 40.3.mat as it has already been processed
Skipping 5.1.mat as it has already been processed
Skipping 5.2.mat as it has already been processed

In [48]:
df = c.get_dataframe() # returns a pandas dataframe of the processed data
df

Loading data for anestis...
Loading data for chris...
Loading data for dim_tselios...
Loading data for dwrotheos...
Loading data for giannatos...
Loading data for iatroudelis...
Loading data for kiosses...
Loading data for konstantopoulos...
Loading data for leonidas...
Loading data for malidakis...
Loading data for manos...
Loading data for mavrokefalidis...
Loading data for mpardas...
Loading data for nastos-jr...
Loading data for nastos-sr...
Loading data for nick...
Loading data for nikos...
Loading data for paliaxanis...
Loading data for pavlidis...
Loading data for periklis...
Loading data for polemarchakis...
Loading data for rafa...
Loading data for romas...
Loading data for thanasis...

,subject,mvc_level,trial_number,neuron_data,force_data
0,anestis,5,1,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]...","[0.0, 0.0, 0.0, 0.006100465392307797, -0.00610..."
1,anestis,5,2,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.0, 0.012200930784608488, 0.0122009307846084..."
2,anestis,5,3,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.0, -0.006100465392300691, 0.0, 0.0061004653..."
3,anestis,10,1,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]...","[0.0, 0.006100465392300691, 0.0, -0.0061004653..."
4,anestis,10,2,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.0, 0.0, 0.0, 0.0, -0.006100465392307797, 0...."
...,...,...,...,...,...
393,thanasis,60,1,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.0, -0.006100465392304244, -0.00610046539230..."
394,thanasis,60,2,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.0, 0.01830139617690918, 0.00610046539230424..."
395,thanasis,60,3,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.0, -0.006100465392304244, 0.0, 0.0061004653..."
396,thanasis,100,1,None,"[0.0, 0.006100465392304244, 0.0122009307846049..."
397,thanasis,100,2,None,"[0.0, 0.0, 0.006100465392304244, 0.00610046539..."

### Sanitization

Remove or correct any errors in the data. This includes removing outliers, filling in missing values, and correcting any other errors in the data. Some entries are not recoverable and will be "purged".

Below are the sanitization steps that will be taken:

#### Lack of neurons (`N`) — Purge
Number of recorded neurons (expect Max MVC) is below some acceptable constant value.

#### Spike (`S`)
An intense and major deviation from regular force trend.

#### Neuron Inconsistency (`NI`) — Purge
Major inconsistencies or large distances between activation times in vertically aligned neurons.

#### Measurement Decorrelation (`MD`) — Purge?
Discrepancies between measured neuron activations and force readings. An abundance of discrepancies (`MD`) in the dataset leads to General Measurement Decorrelation (`GMD`) and marshals a purge. 

#### Trend (`T`) — Purge
Force trend has a significant deviation from typical (average) force trend of it's peers. This feature ignores magnitude and strictly considers the relative shape in relation to others. 

More information and specific algorithm implementations can be found [here](https://github.com/paul-bokelman/force-prediction/issues/3).

In [53]:
import importlib
import sanitization.sanitization
import sanitization.constants

importlib.reload(sanitization.sanitization)
importlib.reload(sanitization.constants)

from sanitization.sanitization import Sanitization

sanitizer = Sanitization(df=df)
sdf = sanitizer.sanitize()

Purging entries with insufficient neuron data...
Purged 88 entries with insufficient neuron data. 310 entries remaining.

In [54]:
sdf[sdf["subject"] == "malidakis"]

,subject,mvc_level,trial_number,neuron_data,force_data
150,malidakis,5,1,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0....","[0.0, 0.0, -0.006100465392302468, -0.006100465..."
151,malidakis,5,2,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0....","[0.0, 0.0, 0.0, -0.006100465392304244, 0.0, -0..."
152,malidakis,5,3,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0....","[0.0, -0.006100465392302468, -0.01220093078460..."
153,malidakis,10,1,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.0, 0.0, 0.0, 0.006100465392302468, 0.012200..."
154,malidakis,10,2,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.0, 0.012200930784606712, -0.006100465392304..."
155,malidakis,10,3,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.0, -0.006100465392302468, -0.00610046539230..."
156,malidakis,20,1,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.0, 0.0, -0.006100465392302468, -0.006100465..."
157,malidakis,20,2,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.0, 0.006100465392304244, 0.0122009307846084..."
158,malidakis,20,3,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.0, 0.0, 0.0, -0.006100465392304244, -0.0183..."
159,malidakis,40,1,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.0, 0.006100465392304244, 0.0061004653923042..."
160,malidakis,40,2,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.0, -0.006100465392302468, 0.0, -0.012200930..."
161,malidakis,40,3,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.0, 0.006100465392304244, 0.0061004653923042..."
163,malidakis,60,2,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0....","[0.0, 0.006100465392304244, -0.006100465392304..."
164,malidakis,60,3,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0....","[0.0, -0.006100465392304244, -0.00610046539230..."